//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class summeryTBL
    {
        public int Id { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string title { get; set; }
        public string author { get; set; }
    }
}
